name: jobs_flutter_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts: 3.0.1
  flutter_screenutil: 5.5.4
  heroicons: any
  cached_network_image: any
  flutter_svg: 1.1.5
  lottie: 1.4.2
  modal_bottom_sheet: 2.1.2
  carousel_slider: 4.1.1
  dots_indicator: 2.1.0
  flutter_markdown: 0.6.12
  persistent_bottom_nav_bar_v2: 4.2.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

